### ISSUE TITLE
stemming for '0181,'  throws error. undefined method `stem' for "0181,":String

### ISSUE THREAD

**Issue by krishaish** [domnikl/highscore#29]
I know stemming cannot happen for this. but please handle if possible.

**Comment by domnikl** [comment]
did you forget to load fast-stemmer or stemmer?

```ruby
require 'fast_stemmer'
=> true
"0181,".stem
=> "0181,"
```

Stemming is only used if one of these is loaded, otherwise, there is no call to `.stem` (https://github.com/domnikl/highscore/blob/master/lib/highscore/content.rb#L220)
