### ISSUE TITLE
non english words?

### ISSUE THREAD

**Issue by mibamur** [domnikl/highscore#30]
Hi!
How could I add others locales support?

**Comment by domnikl** [comment]
Hi @mibamur,
what do you mean? The rating is in general not dependant on the language. You can add a blacklist only for a specific language and the stemming won't work with languages other than english. Everything else is just counting words.

**Comment by mibamur** [comment]
@domnikl sorry
low level understanding
I had some troubles with unicode utf8
now it is worked fine
