### ISSUE TITLE
Bloomfilter bucket gets filled up depending on size of list and raises exception

### ISSUE THREAD

**Issue by mhfs** [domnikl/highscore#31]
Hi there,

Using the words [here](https://github.com/ealdent/lda-ruby/blob/master/lib/lda-ruby/config/stopwords.yml) as a blacklist, I get the following error when trying to initialize it.

Steps to reproduce

``` ruby
words = YAML.load_file 'stopwords.yml'
Highscore::Blacklist.load(words)
```

```
RuntimeError: bucket got filled up
    ./bloomfilter-rb-2.1.1/lib/bloomfilter/native.rb:24:in `insert'
    ./bloomfilter-rb-2.1.1/lib/bloomfilter/native.rb:24:in `insert'
    ./highscore-1.2.0/lib/highscore/wordlist.rb:115:in `block in init_bloom_filter'
    ./highscore-1.2.0/lib/highscore/wordlist.rb:47:in `block in each'
    ./highscore-1.2.0/lib/highscore/wordlist.rb:47:in `each'
    ./highscore-1.2.0/lib/highscore/wordlist.rb:47:in `each'
    ./highscore-1.2.0/lib/highscore/wordlist.rb:115:in `init_bloom_filter'
    ./highscore-1.2.0/lib/highscore/wordlist.rb:41:in `initialize'
```

Here are the params used for the bloomfilter creation when that list is supplied.

``` ruby
{ :size => 22800, :bucket => 4, :raise => true, :hashes => 28 }
```

**Comment by thoughtpunch** [comment]
@mhfs I ran into the same issue as well. It's because the bloomfilter-rb lib has a hard-coded size of 100. If you pass in 100 or less items it works fine

Here's the culprit https://github.com/igrigorik/bloomfilter-rb/blob/master/lib/bloomfilter/native.rb#L9

**Comment by domnikl** [comment]
As @thoughtpunch said, it's an issue with bloomfilter-rb
